# Generated by Django 3.1.4 on 2021-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=300)),
                ('Pub_date', models.DateField()),
            ],
        ),
    ]
