# Generated by Django 3.1.4 on 2022-01-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('User_Type', models.CharField(max_length=50)),
            ],
        ),
    ]
